version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
  web:
    image: nginx:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
    links:
      - php
  php:
    #remove this
    #dockerfile: extensions
    #image: php:7-fpm
    build:
      context: .
      dockerfile: Dockerfile
    #change with build ...
    #build: './images/php'
    links:
      - mysql
    volumes:
      - ./www:/var/www
  mysql:
    image: mysql
    
    ports:
      - "3306:3306"
    #volumes:
    #  - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
    environment:
        MYSQL_ROOT_PASSWORD: secret
